
```{r}
library(sf)
library(tidyverse)
library(GWmodel)    
library(tmap)   
library(spdep)
```
```{r}
data <- st_read("plots/regression.shp")
```

```{r}
data = st_transform(data, "EPSG:27700")
```

```{r}
scaled_data <- data.frame(
  DWGVI = scale(data$DWGVI),
  SGVI = scale(data$Scenic_GVI),
  CGVI = scale(data$Constant_G),
  OGVI = scale(data$Original_G),
  SNDVI = scale(data$avg_ndvi),
  STEMP = scale(data$avg_temp),
  POPDENS = scale(data$popdens),
  LSOA11CD = data$LSOA11CD,
  geometry = data$geometry
)

scaled_data <- st_as_sf(scaled_data)
```

```{r}
#--------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------
# model 1 
```

```{r}
x_var1<-"OGVI"
```

```{r}
formula_1 <- as.formula(paste("STEMP ~", x_var, "+ POPDENS"))
```

```{r}
m1 = lm(formula_1, data = scaled_data) 
summary(m1)
```
```{r}
vif(m1)
```

```{r}
residuals_m1 <- resid(m1)
scaled_data$residuals_m1 = residuals_m1
tm_shape(scaled_data) + 
  tm_polygons('residuals_m1', breaks = c(min(resids_m1), -1.5, 1.5, max(resids_m1)), 
              palette = c("indianred1","antiquewhite2","powderblue"), 
              title = "M1 Residuals") +
tm_layout(legend.format= list(digits = 1), frame = F) 
```

```{r}
lsoa_nb <- poly2nb(scaled_data,snap = 0.1) 
lsoa_lw = nb2listw(lsoa_nb)
moran.test(scaled_data$residuals_m1, lsoa_lw)
```

```{r}
data_sp = as(scaled_data, "Spatial")
```

```{r}
bw1 <- bw.gwr(formula_1, 
                approach = "AIC", 
                adaptive = F, 
                data = data_sp)
  
bw1
```
```{r}
gwr_m1 <- gwr.basic(formula_1, 
                     adaptive = T, 
                     data = data_sp, 
                     bw = bw1)
gwr_m1
```


```{r}
gwr_sf1 = st_as_sf(gwr_m1$SDF)
gwr_sf1
```


```{r}
tm7a<-tm_shape(gwr_sf1) +
  tm_fill(c("OGVI"),midpoint = 0, style = "kmeans",title = "Local coefficients of OGVI") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(a)", position=c(0,0.85), size=1.5)
tm7a
```

```{r}
tm7b<-tm_shape(gwr_sf1) +
  tm_fill(c("POPDENS"),midpoint = 0, style = "kmeans",title = "Local coefficients of POPDENS") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(b)", position=c(0,0.85), size=1.5)
tm7b
```
```{r}
tm7c<-tm_shape(gwr_sf1) +
  tm_fill(c("Local_R2"),midpoint = 0, style = "kmeans", title = "Local_R2 of M7") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(c)", position=c(0,0.85), size=1.5)
tm7c
```


```{r}
#--------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------
# model 2
```


```{r}
x_var2<-"CGVI"
```

```{r}
formula_2 <- as.formula(paste("STEMP ~", x_var2, "+ POPDENS"))
```

```{r}
m2 = lm(formula_2, data = scaled_data) 
summary(m2)
```
```{r}
vif(m2)
```

```{r}
residuals_m2 <- resid(m2)
scaled_data$residuals_m2 = residuals_m2
tm_shape(scaled_data) + 
  tm_polygons('residuals_m2', breaks = c(min(resids_m2), -1.5, 1.5, max(resids_m2)), 
              palette = c("indianred1","antiquewhite2","powderblue"), 
              title = "M2 Residuals") +
tm_layout(legend.format= list(digits = 1), frame = F) 
```
```{r}
moran.test(scaled_data$residuals_m2, lsoa_lw) 
```
```{r}
data_sp = as(scaled_data, "Spatial")
```

```{r}
bw2 <- bw.gwr(formula_2, 
                approach = "AIC", 
                adaptive = F, 
                data = data_sp)
  
bw2
```
```{r}
gwr_m2 <- gwr.basic(formula_2, 
                     adaptive = T, 
                     data = data_sp, 
                     bw = bw2)
gwr_m2
```
```{r}
gwr_sf2 = st_as_sf(gwr_m2$SDF)
gwr_sf2
```

```{r}
tm8a<-tm_shape(gwr_sf2) +
  tm_fill(c("CGVI"),midpoint = 0, style = "kmeans",title = "Local coefficients of CGVI") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(d)", position=c(0,0.85), size=1.5)
tm8a
```

```{r}
tm8b<-tm_shape(gwr_sf2) +
  tm_fill(c("POPDENS"),midpoint = 0, style = "kmeans",title = "Local coefficients of POPDENS") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(e)", position=c(0,0.85), size=1.5)
tm8b
```
```{r}
tm8c<-tm_shape(gwr_sf2) +
  tm_fill(c("Local_R2"),midpoint = 0, style = "kmeans", title = "Local_R2 of M8") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(f)", position=c(0,0.85), size=1.5)
tm8c
```

```{r}
#--------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------
# model 3 
```

```{r}
x_var3<-"SGVI"
```

```{r}
formula_3 <- as.formula(paste("STEMP ~", x_var3, "+ POPDENS"))
```

```{r}
m3 = lm(formula_3, data = scaled_data) 
summary(m3)
```
```{r}
vif(m3)
```

```{r}

residuals_m3 <- resid(m3)
scaled_data$residuals_m3 = residuals_m3

tm_shape(scaled_data) + 
  tm_polygons('residuals_m3', breaks = c(min(resids_m3), -1.5, 1.5, max(resids_m3)), 
              palette = c("indianred1","antiquewhite2","powderblue"), 
              title = "M3 Residuals") +
tm_layout(legend.format= list(digits = 1), frame = F) 
```
```{r}
moran.test(scaled_data$residuals_m3, lsoa_lw) 
```
```{r}
data_sp = as(scaled_data, "Spatial")
```

```{r}

bw3 <- bw.gwr(formula_3, 
                approach = "AIC", 
                adaptive = F, 
                data = data_sp)
  
bw3
```
```{r}

gwr_m3 <- gwr.basic(formula_3, 
                     adaptive = T, 
                     data = data_sp, 
                     bw = bw3)
gwr_m3
```
```{r}
gwr_sf3 = st_as_sf(gwr_m3$SDF)
gwr_sf3
```

```{r}
tm9a<-tm_shape(gwr_sf3) +
  tm_fill(c("SGVI"),midpoint = 0, style = "kmeans",title = "Local coefficients of SGVI") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(g)", position=c(0,0.85), size=1.5)
tm9a
```

```{r}
tm9b<-tm_shape(gwr_sf3) +
  tm_fill(c("POPDENS"),midpoint = 0, style = "kmeans",title = "Local coefficients of POPDENS") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(h)", position=c(0,0.85), size=1.5)
tm9b
```
```{r}
tm9c<-tm_shape(gwr_sf3) +
  tm_fill(c("Local_R2"),midpoint = 0, style = "kmeans", title = "Local_R2 of M9") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(i)", position=c(0,0.85), size=1.5)
tm9c
```


```{r}
#--------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------
# model 4 
```

```{r}
x_var4<-"DWGVI"
```

```{r}
formula_4 <- as.formula(paste("STEMP ~", x_var4, "+ POPDENS"))
```

```{r}
m4 = lm(formula_4, data = scaled_data) 
summary(m4)
```
```{r}
vif(m4)
```

```{r}

residuals_m4 <- resid(m4)
scaled_data$residuals_m4 = residuals_m4

tm_shape(scaled_data) + 
  tm_polygons('residuals_m4', breaks = c(min(resids_m4), -1.5, 1.5, max(resids_m4)), 
              palette = c("indianred1","antiquewhite2","powderblue"), 
              title = "M4 Residuals") +
tm_layout(legend.format= list(digits = 1), frame = F) 
```
```{r}
moran.test(scaled_data$residuals_m4, lsoa_lw) 
```
```{r}
data_sp = as(scaled_data, "Spatial")
```

```{r}

bw4 <- bw.gwr(formula_4, 
                approach = "AIC", 
                adaptive = F, 
                data = data_sp)
  
bw4
```
```{r}

gwr_m4 <- gwr.basic(formula_4, 
                     adaptive = T, 
                     data = data_sp, 
                     bw = bw4)
gwr_m4
```
```{r}
gwr_sf4 = st_as_sf(gwr_m4$SDF)
gwr_sf4
```

```{r}
tm10a<-tm_shape(gwr_sf4) +
  tm_fill(c("DWGVI"),midpoint = 0, style = "kmeans",title = "Local coefficients of DGVI") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(j)", position=c(0,0.85), size=1.5)
tm10a
```

```{r}
tm10b<-tm_shape(gwr_sf4) +
  tm_fill(c("POPDENS"),midpoint = 0, style = "kmeans",title = "Local coefficients of POPDENS") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(k)", position=c(0,0.85), size=1.5)
tm10b
```
```{r}
tm10c<-tm_shape(gwr_sf4) +
  tm_fill(c("Local_R2"),midpoint = 0, style = "kmeans", title = "Local_R2 of M10") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(l)", position=c(0,0.85), size=1.5)
tm10c
```


```{r}
#--------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------
# model 5
```

```{r}
x_var5<-"SNDVI"
```

```{r}
formula_5 <- as.formula(paste("STEMP ~", x_var5, "+ POPDENS"))
```

```{r}
m5 = lm(formula_5, data = scaled_data) 
summary(m5)
```
```{r}
vif(m5)
```

```{r}

residuals_m5 <- resid(m5)
scaled_data$residuals_m5 = residuals_m5

tm_shape(scaled_data) + 
  tm_polygons('residuals_m5', breaks = c(min(resids_m5), -1.5, 1.5, max(resids_m5)), 
              palette = c("indianred1","antiquewhite2","powderblue"), 
              title = "M5 Residuals") +
tm_layout(legend.format= list(digits = 1), frame = F) 
```
```{r}
moran.test(scaled_data$residuals_m5, lsoa_lw) 
```
```{r}
data_sp = as(scaled_data, "Spatial")
```

```{r}

bw5 <- bw.gwr(formula_5, 
                approach = "AIC", 
                adaptive = F, 
                data = data_sp)
  
bw5
```
```{r}
gwr_m5 <- gwr.basic(formula_5, 
                     adaptive = T, 
                     data = data_sp, 
                     bw = bw5)
gwr_m5
```
```{r}
gwr_sf5 = st_as_sf(gwr_m5$SDF)
gwr_sf5
```

```{r}
tm11a<-tm_shape(gwr_sf5) +
  tm_fill(c("SNDVI"),midpoint = 0, style = "kmeans",title = "Local coefficients of SNDVI") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(m)", position=c(0,0.85), size=1.5)
tm11a
```

```{r}
tm11b<-tm_shape(gwr_sf5) +
  tm_fill(c("POPDENS"),midpoint = 0, style = "kmeans",title = "Local coefficients of POPDENS") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(n)", position=c(0,0.85), size=1.5)
tm11b
```
```{r}
tm11c<-tm_shape(gwr_sf5) +
  tm_fill(c("Local_R2"),midpoint = 0, style = "kmeans", title = "Local_R2 of M11") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(o)", position=c(0,0.85), size=1.5)
tm11c
```

```{r}
#--------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------
# model 6
```

```{r}
x_var6<-"OGVI + SNDVI"
```

```{r}
formula_6 <- as.formula(paste("STEMP ~", x_var6, "+ POPDENS"))
```

```{r}
m6 = lm(formula_6, data = scaled_data) 
summary(m6)
```
```{r}
vif(m6)
```

```{r}

residuals_m6 <- resid(m6)
scaled_data$residuals_m6 = residuals_m6

tm_shape(scaled_data) + 
  tm_polygons('residuals_m6', breaks = c(min(resids_m6), -1.5, 1.5, max(resids_m6)), 
              palette = c("indianred1","antiquewhite2","powderblue"), 
              title = "M6 Residuals") +
tm_layout(legend.format= list(digits = 1), frame = F) 
```
```{r}
moran.test(scaled_data$residuals_m6, lsoa_lw) 
```
```{r}
data_sp = as(scaled_data, "Spatial")
```

```{r}

bw6 <- bw.gwr(formula_6, 
                approach = "AIC", 
                adaptive = F, 
                data = data_sp)
  
bw6
```
```{r}

gwr_m6 <- gwr.basic(formula_6, 
                     adaptive = T, 
                     data = data_sp, 
                     bw = bw6)
gwr_m6
```
```{r}
gwr_sf6 = st_as_sf(gwr_m6$SDF)
gwr_sf6
```

```{r}
tm12a<-tm_shape(gwr_sf6) +
  tm_fill(c("OGVI"),midpoint = 0, style = "kmeans",title = "Local coefficients of OGVI") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(p)", position=c(0,0.85), size=1.5)
tm12a
```

```{r}
tm12b<-tm_shape(gwr_sf6) +
  tm_fill(c("SNDVI"),midpoint = 0, style = "kmeans",title = "Local coefficients of SNDVI") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(q)", position=c(0,0.85), size=1.5)
tm12b
```

```{r}
tm12c<-tm_shape(gwr_sf6) +
  tm_fill(c("POPDENS"),midpoint = 0, style = "kmeans",title = "Local coefficients of POPDENS") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(r)", position=c(0,0.85), size=1.5)
tm12c
```
```{r}
tm12d<-tm_shape(gwr_sf6) +
  tm_fill(c("Local_R2"),midpoint = 0, style = "kmeans", title = "Local_R2 of M12") +
  tm_style("col_blind")+
  tm_layout(legend.position = c("right","top"),legend.outside = F, frame = F) +
  tm_compass(type = "arrow", position = c(0.02, 0), size = 2) + 
  tm_scale_bar(position = c(0.7, 0), width = 0.15) +
  tm_credits("(s)", position=c(0,0.85), size=1.5)
tm12d
```



```{r}
tm_all=tmap_arrange(tm7a, tm7b, tm7c, tm8a, tm8b, tm8c,tm9a, tm9b, tm9c, tm10a, tm10b, tm10c,tm11a, tm11b, tm11c,tm12a, tm12b, tm12c, tm12d, ncol=3)

tm_all
```

```{r}
tmap_save(tm_all, filename = "789.png", width = 5000, height = 7000)
```


